name: Publish Docker
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/ArtashMardoyan/nest-top-api/nest-top-api
          username: artashmardoyan
          password: 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
          tags: "develop"